### ISSUE TITLE
Add 'onLocationUpdate' parameter

### ISSUE THREAD

**Issue by jesusrp98** [igaurab/user_location_plugin#12]
Inside the `UserLocationOptions` class, add a new `onLocationUpdate`, which would be called once user's location has changed.

This example here would print the location every time it changes.
```
UserLocationOptions(
  context: context,
  ...
  onLocationUpdate: (LatLng pos) => print(pos),
)

**Comment by konishon** [comment]
In the current implementation, you can achieve this by defining a  stream and passing it on to the plugin. The plugin updates the stream, which can then be listened to for updates
```dart
    StreamController<LatLng> markerlocationStream = StreamController();
    markerlocationStream.stream.listen((onData) {
      print(onData.latitude);
    });
```
```dart
UserLocationOptions(
  context: context,
  ...
 markerlocationStream: stream,
)

```
but @jesusrp98 proposal to pass a function instead is neater what do you think @igaurab  ?

**Comment by jesusrp98** [comment]
I'm currently using that exact scheme, based on the example project provided with the package, and I find it a bit cumbersome.

But that way you're forcing the developers use a patter like `Streams` in order to retrieve the location. I think providing a simpler option, like the one I provided is ideal.
