### ISSUE TITLE
Add 'updateMapOnStart' parameter

### ISSUE THREAD

**Issue by jesusrp98** [igaurab/user_location_plugin#13]
This optional parameter would update map's center always the first time it runs.

This option doesn't have much sense if the `updateMapLocationOnPositionChange` parameter is set to `true`, because the map will be always updated. It makes more sense once that other parameters is set to `false`. The map would start with the user front and center, but it wouldn't update map's center every time it moves.

```
UserLocationOptions(
  context: context,
  ...
  updateMapOnStart: true,
  updateMapLocationOnPositionChange: false,
)
```

**Comment by igaurab** [comment]
@jesusrp98 in #25 I have added a paramter `zoomToCurrentLocationOnLoad` which zooms the map to the current location on start.
