### ISSUE TITLE
Show heading of user location marker

### ISSUE THREAD

**Issue by konishon** [igaurab/user_location_plugin#18]
**Is your feature request related to a problem? Please describe.**
The heading of the device is not shown on user location marker

**Describe the solution you'd like**
Show the heading in user location marker, something similar to google maps might be good place to start

**Describe alternatives you've considered**

**Additional context**
I am using this library and implemented routing, So, it would be nice to know where the user is heading. 
Making use of [simple_flutter_compass](https://pub.dev/packages/simple_flutter_compass#simple_flutter_compass) might be a good place to start
or [compass_in_android](https://stackoverflow.com/a/20340147)

**Comment by igaurab** [comment]
This issue is addressed in #31
