### ISSUE TITLE
What is the minimum supported version of flutter_Map

### ISSUE THREAD

**Issue by Huai-Dc** [igaurab/user_location_plugin#2]

**Comment by Huai-Dc** [comment]
Because every version of user_location depends on flutter_map from hosted and mz_flutterapp_deep depends on flutter_map from path, user_location is forbidden

can turn this limit off

**Comment by igaurab** [comment]
@Huai-Dc I have build the plugin based on the recent version of flutter_map ie 0.7. I have not tested the plugin with the older versions of flutter map. Are you facing any issues with the plugin? Please let me know ;)

**Comment by Huai-Dc** [comment]
> @Huai-Dc I have build the plugin based on the recent version of flutter_map ie 0.7. I have not tested the plugin with the older versions of flutter map. Are you facing any issues with the plugin? Please let me know ;)

The current version of flutter is based on 1.5.4 and the flutter is 0.5.5. we made some changes on this versions （0.5.5）. and now i‘m fix some error in this version but  user_location is forbidden it from path
