### ISSUE TITLE
Markers doesn't render properly

### ISSUE THREAD

**Issue by jesusrp98** [igaurab/user_location_plugin#3]
I'm trying to render a list of markers, generated by data inside a Provider model.

```
FlutterMap(
  mapController: mapController,
  options: MapOptions(
    zoom: 17,
    minZoom: 5,
    maxZoom: 19,
    plugins: [
      UserLocationPlugin(),
    ],
  ),
  layers: [
    TileLayerOptions(
      urlTemplate: model.mapUrl,
      backgroundColor: Theme.of(context).canvasColor,
    ),
    MarkerLayerOptions(
      markers: [
        for (Museum museum in model.items)
          MapPin(
            title: museum.name,
            subtitle: museum.city,
            id: museum.id,
            location: museum.location,
          )
      ],
    ),
    UserLocationOptions(
      context: context,
      mapController: mapController,
      markers: ???,
    ),
  ],
)
```
Also, should I add the same markers inside the `UserLocationOptions` object? Documentation doesn't tell it clearly, since it's using an empty list :/

The `MapPin` object derives from the Marker class, there were no problem rendering them before implementing this package into the project.

**Comment by igaurab** [comment]
Hi, thank you for mentioning that out. 
You should make use a of  separate marker list object and pass it in  `UserLocationOptions`

**Comment by jesusrp98** [comment]
That doesn't make much sense to me. Why is mandatory to add the markers to two different places?
Also, I've noticed that if you don't use a map controller, it wouldn't work.

**Comment by igaurab** [comment]
@jesusrp98 in the current implementation, every time the user changes his location, the list of marker is cleared and a new marker with the new user location is plotted in the map. A possible solution to this could be adding the marker at the end of the markers list and only removing the last marker object. 

`MapController` here is used to move the camera to the current location of the user, I'll look into the issue. Thanks.

**Comment by boris612** [comment]
@igaurab 
> You should make use a of separate marker list object and pass it in `UserLocationOptions`

If you use another marker list in UserLocationOptions then only the list set in MarkerLayerOptions of FlutterMap is used.
