### ISSUE TITLE
When the phone rotate, the current location marker does not rotated

### ISSUE THREAD

**Issue by amokio** [igaurab/user_location_plugin#35]
When the phone rotate, the current location marker does not rotated.

The direction state have no updated??

**Comment by igaurab** [comment]
Hi, do you mean the heading?

**Comment by amokio** [comment]
the _markers is state. It will get other marker coordinate by calling API when user location change. however, when my physical device angle change, the user location that present the angle shape have no update.
Also, there existing another error: 

```
E/EventChannel#locationStatusStream(25617): Failed to close existing event stream
E/EventChannel#locationStatusStream(25617): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p0
E/EventChannel#locationStatusStream(25617): 	at com.example.user_location.UserLocationPlugin$Companion$registerWith$1.onCancel(Unknown Source:2)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:187)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/EventChannel#locationStatusStream(25617): 	at android.os.Looper.loop(Looper.java:174)
E/EventChannel#locationStatusStream(25617): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/EventChannel#locationStatusStream(25617): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```


Here is my code.
```
@override
  Widget build(BuildContext context) {
    _userLocationOptions = UserLocationOptions(
        context: context,
        mapController: _mapController,
        markers: _markers,
        onLocationUpdate: onLocationUpdated,
        updateMapLocationOnPositionChange: true,
        showMoveToCurrentLocationFloatingActionButton: true,
        zoomToCurrentLocationOnLoad: false,
        fabBottom: 50,
        fabRight: 50,
        verbose: false);

    _markerClusterLayerOptions = MarkerClusterLayerOptions(
        maxClusterRadius: 120,
        size: Size(40, 40),
        fitBoundsOptions: FitBoundsOptions(
          padding: EdgeInsets.all(50),
        ),
        markers: [..._markers],
        polygonOptions: PolygonOptions(
            borderColor: Colors.blueAccent,
            color: Colors.black12,
            borderStrokeWidth: 3),
        builder: (context, marker) {
          return FloatingActionButton(
            child: Text(marker.length.toString()),
            onPressed: null,
          );
        },
        onMarkerTap: (marker) {});

    return Scaffold(
      body: FlutterMap(
        options: MapOptions(
          center: LatLng(27.7172, 85.3240),
          zoom: 13.0,
          plugins: [
            UserLocationPlugin(),
            MarkerClusterPlugin(),
            MyCustomPlugin(),
          ],
        ),
        layers: [
          TileLayerOptions(
            urlTemplate: "https://api.tiles.mapbox.com/v4/"
                "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
            additionalOptions: {
              'accessToken':
                  '<token>',
              'id': 'mapbox.streets',
            },
          ),
          MyCustomPluginOptions(text: "I'm a plugin!"),
          // MarkerLayerOptions(markers: markers),
          _markerClusterLayerOptions,
          _userLocationOptions,
        ],
        mapController: _mapController,
      ),
    );
  }
```

**Comment by amokio** [comment]
> Hi, do you mean the heading?

Yes. i mean the heading

@igaurab can you also please update the pub version? because you merged the code but not yet update

**Comment by igaurab** [comment]
@mattia-lau sure.

[UPDATE] The new version is 0.1.2 which includes the changes

**Comment by igaurab** [comment]
@amias-samir dai, could you please look into it, when you are free.

**Comment by MildConcussion** [comment]
Awesome work!

Direction marker has been working for me since 0.1.1, but now on 0.1.2 it prints Direction debug to console.

**Comment by amokio** [comment]
> Awesome work!
> 
> Direction marker has been working for me since 0.1.1, but now on 0.1.2 it prints Direction debug to console.

The heading is also work fine for you?? when your phone rotated, the heading have changed also?

**Comment by amokio** [comment]
@igaurab new problem here. After dispose the widget and enter the same widget again.
```
E/EventChannel#locationStatusStream(25617): Failed to close existing event stream
E/EventChannel#locationStatusStream(25617): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p0
E/EventChannel#locationStatusStream(25617): 	at com.example.user_location.UserLocationPlugin$Companion$registerWith$1.onCancel(Unknown Source:2)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:187)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/EventChannel#locationStatusStream(25617): 	at android.os.Looper.loop(Looper.java:174)
E/EventChannel#locationStatusStream(25617): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/EventChannel#locationStatusStream(25617): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by konishon** [comment]
> @igaurab new problem here. After dispose the widget and enter the same widget again.
> 
> ```
> E/EventChannel#locationStatusStream(25617): Failed to close existing event stream
> E/EventChannel#locationStatusStream(25617): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p0
> E/EventChannel#locationStatusStream(25617): 	at com.example.user_location.UserLocationPlugin$Companion$registerWith$1.onCancel(Unknown Source:2)
> E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:187)
> E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
> E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
> E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
> E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.next(MessageQueue.java:336)
> E/EventChannel#locationStatusStream(25617): 	at android.os.Looper.loop(Looper.java:174)
> E/EventChannel#locationStatusStream(25617): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
> E/EventChannel#locationStatusStream(25617): 	at java.lang.reflect.Method.invoke(Native Method)
> E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> ```

This is going beyond the scope of this issue. @mattia-lau Would you mind creating a new one for this?

**Comment by amokio** [comment]
> > @igaurab new problem here. After dispose the widget and enter the same widget again.
> > ```
> > E/EventChannel#locationStatusStream(25617): Failed to close existing event stream
> > E/EventChannel#locationStatusStream(25617): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p0
> > E/EventChannel#locationStatusStream(25617): 	at com.example.user_location.UserLocationPlugin$Companion$registerWith$1.onCancel(Unknown Source:2)
> > E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:187)
> > E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
> > E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
> > E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
> > E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> > E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.next(MessageQueue.java:336)
> > E/EventChannel#locationStatusStream(25617): 	at android.os.Looper.loop(Looper.java:174)
> > E/EventChannel#locationStatusStream(25617): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
> > E/EventChannel#locationStatusStream(25617): 	at java.lang.reflect.Method.invoke(Native Method)
> > E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> > E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> > ```
> 
> This is going beyond the scope of this issue. @mattia-lau Would you mind creating a new one for this?

Sorry what do you mean for creating a new one? You mean new issue?

and i wonder to know how to make sure my Plugin is on top of the layer?
I want to make sure my input field is on top of the layer. But now, the heading is on top of my input field

**Comment by konishon** [comment]
> > > @igaurab new problem here. After dispose the widget and enter the same widget again.
> > > ```
> > > E/EventChannel#locationStatusStream(25617): Failed to close existing event stream
> > > E/EventChannel#locationStatusStream(25617): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p0
> > > E/EventChannel#locationStatusStream(25617): 	at com.example.user_location.UserLocationPlugin$Companion$registerWith$1.onCancel(Unknown Source:2)
> > > E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:187)
> > > E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
> > > E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
> > > E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
> > > E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> > > E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.next(MessageQueue.java:336)
> > > E/EventChannel#locationStatusStream(25617): 	at android.os.Looper.loop(Looper.java:174)
> > > E/EventChannel#locationStatusStream(25617): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
> > > E/EventChannel#locationStatusStream(25617): 	at java.lang.reflect.Method.invoke(Native Method)
> > > E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> > > E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> > > ```
> > 
> > 
> > This is going beyond the scope of this issue. @mattia-lau Would you mind creating a new one for this?
> 
> Sorry what do you mean for creating a new one? You mean new issue?
> 
> and i wonder to know how to make sure my Plugin is on top of the layer?
> I want to make sure my input field is on top of the layer. But now, the heading is on top of my input field

Yes! Let's create a new issue for `E/EventChannel#locationStatusStream(25617): Failed to close existing event stream`

**Comment by konishon** [comment]
@mattia-lau 
You could change the order in layers in FlutterMap, to change how each layer shows in the map.

**Comment by mattia-lau** [comment]
> @mattia-lau
> You could change the order in layers in FlutterMap, to change how each layer shows in the map.

i dont really understand your meaning. Any code to take reference?
