### ISSUE TITLE
how to add back to positioning button

### ISSUE THREAD

**Issue by Huai-Dc** [igaurab/user_location_plugin#4]
![Uploading image.png…]()

can I change the icon of the anchor point

**Comment by igaurab** [comment]
Yes, you can do it so by passing your own widget through markerWidget.
For now, there is no way to put your custom accuracy marker. I will look onto that very soon...

**Comment by Huai-Dc** [comment]
> Yes, you can do it so by passing your own widget through markerWidget.
> For now, there is no way to put your custom accuracy marker. I will look onto that very soon...

tks for your replay！and i have a problem the anchor sometimes disappears when adding the marker point and anchor point at the same time

Three is my code

class _MoodMapPageState extends State<MoodMapPage> {
  MapController mapController = MapController();
  List<Marker> markers = <Marker>[
    Marker(
      width: 40.0,
      height:40.0,
      point: LatLng(24.594539, 118.029745),
      builder: (ctx) => Container(
        child: CircleAvatar(
          backgroundImage: new NetworkImage('http://b-ssl.duitang.com/uploads/item/201810/18/20181018162951_kgwzm.thumb.700_0.jpeg'),
          radius: 30.0,
        ),
      ),
    ),
  ];
  StreamController<LatLng> markerlocationStream = StreamController();

  @override
  Widget build(BuildContext context) {
    //Get the current location of marker  
// When you jump to another page and return to it, an error will be reported.
//    markerlocationStream.stream.listen((onData) {
//      print("======================================================");
//      print(onData); // .latitude
//    });
    return Scaffold(
        body: Container(
          child: FlutterMap(
            options: MapOptions(
              center: LatLng(39.9093, 116.3964),
              zoom: 15.0,
              plugins: [
                UserLocationPlugin(),
              ],
            ),
            layers: [
              TileLayerOptions(
//              urlTemplate: "https://api.tiles.mapbox.com/v4/"
//                  "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
                urlTemplate:
                "https://api.mapbox.com/styles/v1/1693202280/ck0yn0iqy0dz91cmgk1j5gtxq/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoiMTY5MzIwMjI4MCIsImEiOiJjanl0cjJ2amswNzJ2M2VvYjZrZmN0eGV5In0.tQ3eBb8QS6M8PxbCZl0iNQ",
                additionalOptions: {
                  'accessToken':
                  'pk.eyJ1IjoiaWdhdXJhYiIsImEiOiJjazFhOWlkN2QwYzA5M2RyNWFvenYzOTV0In0.lzjuSBZC6LcOy_oRENLKCg',
                  'id': 'mapbox.streets',
                },
              ),
              MarkerLayerOptions(markers: markers),
              UserLocationOptions(
                  context: context,
                  mapController: mapController,
                  markers: markers,
                  markerlocationStream: markerlocationStream,
                  markerWidget:  CircleAvatar(
                      backgroundImage: new NetworkImage('http://b-ssl.duitang.com/uploads/item/201501/28/20150128232210_hsrhr.jpeg'),
                      radius: ScreenUtil().setWidth(45),
                    ),,
            ],
            mapController: mapController,
          ),
        )
    );
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    markerlocationStream.close();
  }
}

**Comment by igaurab** [comment]
@Huai-Dc for now you should use separate marker for the user location. I hope that resolves your issue.
