### ISSUE TITLE
Direction is inverted

### ISSUE THREAD

**Issue by javi11** [igaurab/user_location_plugin#55]
Hi, thanks for this great plugin :).

I have a problem at least on a Huawei p30 I don't know if is the phone or if it's the plugin but the direction is inverted on the map. A part of that the speed is not real cause the -2

https://github.com/igaurab/user_location_plugin/blob/744933454a6de886a9ca09975abe678948dd2a65/lib/src/user_location_layer.dart#L133

If I modify this line by:

```dart
(((_direction * -1) ?? 0) * (math.pi / 180) * -1) + 180,
```
All is working as expected.

Is this a real issue or I have something wrong configured?

thanks ;)

**Comment by igaurab** [comment]
Yes, the direction does seem to be a bit off, I'll look into this issue.

**Comment by javi11** [comment]
I can do a PR if you want ;)

**Comment by igaurab** [comment]
@javi11  sure that world be awesome, I tried what you did, it was more precise.

**Comment by igaurab** [comment]
@javi11 hey sorry for the late fix, could you please confirm if #65 fixes the issue?

I tested it in my emulator, it did work

**Comment by javi11** [comment]
Will do now, sorry for no doing the pr, just has to go to other things. Just yesterday I started working on It again.

Thanks for doing the fix btw :)

**Comment by javi11** [comment]
I see it still inverted, maybe for the - 160 that should be or + 180 or + 160

**Comment by javi11** [comment]
Yes with + 160 works perfectly

**Comment by igaurab** [comment]
Thanks for fixing the typo
