### ISSUE TITLE
Version conflicts with flutter_map

### ISSUE THREAD

**Issue by Allenisme** [igaurab/user_location_plugin#58]
Because user_location >=0.1.0 depends on flutter_map ^0.8.2 and community_base depends on flutter_map ^0.9.0, user_location >=0.1.0 is forbidden.

So, because xxx depends on user_location ^0.1.3, version solving failed.
pub get failed (1; So, because community_base depends on user_location ^0.1.3, version solving failed.)

Please update version. Thanks so much. :)

**Comment by igaurab** [comment]
Hi, sorry for the late update, please let me know if it works, also please use the version from git

**Comment by lucasrubini** [comment]
Same error here:

> Because user_location >=0.1.0 depends on flutter_map ^0.8.2 and fiscobra depends on flutter_map ^0.9.0, user_location >=0.1.0 is forbidden.
> 
> So, because *** depends on user_location ^0.1.3, version solving failed.
> pub get failed (1; So, because fiscobra depends on user_location ^0.1.3, version solving failed.)

**Comment by jamontes79** [comment]
The same here

**Comment by igaurab** [comment]
@jamontes79 please try using the latest version from github and let me know if the issue persists

**Comment by jamontes79** [comment]
> @jamontes79 please try using the latest version from github and let me know if the issue persists

Now works. Thanks a lot
