### ISSUE TITLE
Location service crashes the app

### ISSUE THREAD

**Issue by joaotomaspinheiro** [igaurab/user_location_plugin#67]
**Describe the bug**
When I open the app with the location service turned off, it gives me the prompt to ask if I want to enable the location service. If I click 'No Thanks' or 'OK', it reproduces the prompt again and if I choose again 'No Thanks' or 'OK', it crashes the app. This only happens when the app is opened with the location service turned off.

**To Reproduce**
1. Turn off location service
2. Open the app
3. Choose 'No Thanks' or 'OK'

**Expected behavior**
Prompt disappears when 'No Thanks' is clicked or enables location service when 'OK' is clicked.

**Smartphone (please complete the following information):**
 - Device: Samsung A50
 - OS: Android
 - Version 10

**Comment by igaurab** [comment]
Hi which version are you using? The issue was fixed in #59 
Could you please try using the latest version from github, rather than pub and let me know if the problem exist...

**Comment by IonVillarreal** [comment]
hi, the solution is available at pub.dev?

I tried the Github version, but I have the i

**Comment by igaurab** [comment]
Hi,
No, i have not pushed the latest changes to pub.dev, have to migrate the app to v2 #79 , which is still pending after that i maybe i will push the changes.
Please try using it from the Github as of now.
