### ISSUE TITLE
Chaning updateMapLocationOnPositionChange value on runtime doesn't work

### ISSUE THREAD

**Issue by jamontes79** [igaurab/user_location_plugin#69]
I'm changing the value of the property updateMapLocationOnPositionChange on runtime to false but when the location is update the map is moving to the current location.

The idea is deactivate the tracking when the user moves the map and activate again when the user clicks on the center fab button.

Any idea how to deal with it?

Thanks
Regards

**Comment by igaurab** [comment]
Hi,

You can try to make use of the callbacks provided by the flutter_map. Also if possible share your findings, that might help others... 

![image](https://user-images.githubusercontent.com/28226423/86041319-357bf200-ba65-11ea-8d66-3d481e7173b3.png)

You could basically track the position changed and define when to trigger 

`userLocationOptions.updateMapLocationOnPositionChange = false;` 

As of now you cannot provide the callback function to `onPressed` method of the FAB, so re-setting 

`userLocationOptions.updateMapLocationOnPositionChange = true;` might be a problem. I shall add this feature by tomorrow. 

Thanks for raising the issue.

**Comment by jamontes79** [comment]
The new changes works like a charm.

Thanks a lot
