### ISSUE TITLE
Callback for loose location

### ISSUE THREAD

**Issue by jamontes79** [igaurab/user_location_plugin#72]
**My problem is to know when the gps signal is loosed and inform to the user**
I would like to display a message to the user when his position can be updated because the gps signal is loosed. I'm trying with different workarounds but they are not working well

**Possible solution**
I would like a callback in UserLocationOptions to manage that.

Thanks a lot in advance

**Comment by igaurab** [comment]
The plugin has a callback called `onLocationChanged` which can provide you the location updates of the user. You could set some timer and check if his location has been updated in past few x seconds or not, if not you could display the message.

**Comment by jamontes79** [comment]
Thanks I'll think in that solution.

Thanks for your great library and your quickly responses

**Comment by igaurab** [comment]
@jamontes79 I'll be closing this issue as of now....
