### ISSUE TITLE
Add possibility to stop the location update stream to avoid "power intensive background running"

### ISSUE THREAD

**Issue by Xennis** [igaurab/user_location_plugin#74]
**Is your feature request related to a problem? Please describe.**
On Android devices my app is listed as "power intensive apps running in the background" because of "high location frequency". It contains to request the location what is not needed in my case.

**Describe the solution you'd like**
A possibility to stop the location update stream. If I see it correctly the updates can be stopped.

**Comment by igaurab** [comment]
Thanks, it is a nice feature to have.

**Comment by Xennis** [comment]
Hey @igaurab can you point me to the right direction, i.e. what needs to be done for that? I can see that in user_location_layer.dart the `_subscribeToLocationChanges` subscribes to the changes. But how/where to unsubscribe from that location changes (and later subscribe again)? Regards.

**Comment by igaurab** [comment]
Hi, the `userLocationPlugin` makes use of another plugin called `location` to get the current location of the user. It uses `onLocationChange` to subscribe to the location changes, according to their [docs](https://pub.dev/documentation/location/latest/location/Location/changeSettings.html) you can change the interval at which the location updates are checked, that might be the one we should be able to change in runtime.

**Comment by Xennis** [comment]
Hey @igaurab thanks. That helped! I prepared a draft PR: #76 Please have a look. It differs from you idea.

**Comment by Xennis** [comment]
Done in #76 and #77
