### ISSUE TITLE
Plugin keeps the location service on forever

### ISSUE THREAD

**Issue by Xennis** [igaurab/user_location_plugin#78]
**Describe the bug**
If you are using this plugin the location service will be always on even if the app is running in the background. When you are using Google Maps, the [location example](https://github.com/Lyokone/flutterlocation/blob/master/location/example/lib/listen_location.dart), ... you will notice all of them turn the location service off when it's not used. But due to https://github.com/igaurab/user_location_plugin/blob/af89e2dd6c7f8cf91b5398c50ddd6acdd7b56ce3/android/src/main/kotlin/com/example/user_location/UserLocationPlugin.kt#L48 here the location service is kept on ... always.

**To Reproduce**
1. Run the example app
2. You will see the little location icon in the status bar, i.e. the app is accessing the location service.
3. Move the app to the background. The location service will be kept on. You still see the location icon in the status bar.

**Expected behavior**

The location service is not kept on forever. Like the Google Maps app, the [location example](https://github.com/Lyokone/flutterlocation/blob/master/location/example/lib/listen_location.dart), etc. it's off once the app goes into the background.

**Comment by igaurab** [comment]
Thanks for pointing it out. Are you currently working on the issue?

**Comment by Xennis** [comment]
No. I don't know how to fix that directly in Android / iOS but a solution would be nice.
