### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by IonVillarreal** [igaurab/user_location_plugin#95]
Null security support planned ?

**Comment by igaurab** [comment]
yeah will be working on it, but will have to wait a bit longer. Thanks 👍🏿

**Comment by fryette** [comment]
@igaurab seems also latlng should be replaced with latlng2

**Comment by igaurab** [comment]
@fryette thanks

Let me know if you have any other issues/improvement suggestions. Will start working on the issues from tomorrow onwards

**Comment by fryette** [comment]
@igaurab Do you have time to look on it?
